name: main-build

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - uses: EndBug/add-and-commit@v8
        with:
          message: 'CI / CD - Format Updates Automatic Commit'
